server:
  port: 8080

logging:
  level:
    root: info

    com:
      pangpang:
        dockerexample:
          controller: info

spring:
  redis:
    host: #여기 부분은 자신의 ip에 맞춰서 바꾸기 -> ec2 redis 설치 후 연결 ip
      127.0.0.1
    port:
      6379